services:
  quickheadlines:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_REV: ${GIT_COMMIT:-0}
    ports:
      - "3030:3030"
    environment:
      TZ: "America/Chicago"
    volumes:
       - ./feeds.yml:/app/feeds.yml:rw
    restart: unless-stopped
